export const NATURES = [
  "Accidents de la circulation",
  "Incendies et Explosions",
  "Secours et Évacuation",
  "Opérations diverses",
];

export const CATEGORIES: Record<string, string[]> = {
  "Accidents de la circulation": [
    "Voies publiques",
    "Ferroviaire",
    "Maritime",
    "Aérien",
    "Ascenseurs",
    "Autre",
  ],
  "Incendies et Explosions": [
    "IGH (Immeuble Grande Hauteur)",
    "ERP (Établissement Recevant du Public)",
    "Habitations",
    "Installations classées",
    "Couverts végétaux",
    "Véhicules",
    "Autre",
  ],
  "Secours et Évacuation": [
    "Secourisme",
    "Transport sanitaire",
    "Sauvetage",
    "Recherche",
  ],
  "Opérations diverses": [
    "Fuite de gaz",
    "Pollution",
    "Inondations",
    "Sauvetage animaux",
    "Effondrements",
    "Alerte à la bombe",
    "Autre",
  ],
};

export const DAIRAS = [
  "Adekar",
  "Akbou",
  "Amizour",
  "Aokas",
  "Barbacha",
  "Béjaïa",
  "Beni Maouche",
  "Chemini",
  "Darguina",
  "El Kseur",
  "Ighil Ali",
  "Kherrata",
  "Oued Ghir",
  "Seddouk",
  "Sidi Aïch",
  "Souk El Tenine",
  "Tichy",
  "Timezrit",
  "Tazmalt",
];

export const COMMUNES: Record<string, string[]> = {
  "Adekar": ["Adekar", "Taourirt Ighil", "Beni Ksila"],
  "Akbou": ["Akbou", "Chellata", "Ighram", "Tamokra"],
  "Amizour": ["Amizour", "Beni Djellil", "Semaoun", "Ferraoun"],
  "Aokas": ["Aokas", "Tizi N'Berber"],
  "Barbacha": ["Barbacha", "Kendira"],
  "Béjaïa": ["Béjaïa", "Oued Ghir"],
  "Beni Maouche": ["Beni Maouche"],
  "Chemini": ["Chemini", "Tibane", "Souk Oufella", "Akfadou"],
  "Darguina": ["Darguina", "Aït-Smaïl", "Taskriout"],
  "El Kseur": ["El Kseur", "Fenaïa Ilmaten", "Toudja"],
  "Ighil Ali": ["Ighil Ali", "Aït R'zine"],
  "Kherrata": ["Kherrata", "Draâ El-Kaïd"],
  "Oued Ghir": ["Oued Ghir"],
  "Seddouk": ["Seddouk", "Amalou", "M'cisna", "Beni Maouche"],
  "Sidi Aïch": ["Sidi Aïch", "Leflaye", "Tinabdher", "Tifra", "Sidi Ayad"],
  "Souk El Tenine": ["Souk El Tenine", "Melbou", "Tamridjet"],
  "Tichy": ["Tichy", "Boukhelfa"],
  "Timezrit": ["Timezrit"],
  "Tazmalt": ["Tazmalt", "Boudjellil", "Aït-Mellikeche"],
};
